<?php

// $Id: xoops_version.php,v 1.13 2003/04/01 22:51:21 mvandam Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <https://www.xoops.org>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
$modversion['name'] = _MI_ANTIDOS_NAME;
$modversion['version'] = 1.1;
$modversion['description'] = _MI_ANTIDOS_DESC;
$modversion['credits'] = 'PEAK Corp.';
$modversion['author'] = 'GIJ=CHECKMATE<br>PEAK Corp.(http://www.peak.ne.jp/)';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/antidos_slogo.gif';
$modversion['dirname'] = 'antidos';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/myblocksadmin.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Templates

// Blocks
$modversion['blocks'][1]['file'] = 'antidos.php';
$modversion['blocks'][1]['name'] = _MI_ANTIDOS_BNAME1;
$modversion['blocks'][1]['description'] = _MI_ANTIDOS_BDESC1;
$modversion['blocks'][1]['show_func'] = 'b_antidos_show';
$modversion['blocks'][1]['edit_func'] = 'b_antidos_edit';
$modversion['blocks'][1]['options'] = '5|1|5|0';
$modversion['blocks'][1]['template'] = '';

// Menu
$modversion['hasMain'] = 0;

// Search
$modversion['hasSearch'] = 0;

// Comments
$modversion['hasComments'] = 0;

// Config Settings (only for modules that need config settings generated automatically)

// Notification

$modversion['hasNotification'] = 0;

// On Install (turn banip on)
$modversion['onInstall'] = 'include/oninstall.inc.php';
